export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const CHANGE_LOCATION = "CHANGE_LOCATION";
export const LATITUDE_CHANGE = "LATITUDE_CHANGE";
export const LONGITUDE_CHANGE = "LONGITUDE_CHANGE";
export const IS_MAP_LOADED = "IS_MAP_LOADED";
export const TYPE_OF_LOCATION = "TYPE_OF_LOCATION";
export const CHANGE_PLACE_ID = "CHANGE_PLACE_ID";